name: facial_lm_pred
channels:
  - pytorch
  - cvxgrp
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - pip=19.3.1
  - numpy=1.19.1
  - pandas=1.0.5
  - matplotlib=3.1.1
  - pytorch=1.3.1
  - torchvision=0.4.2
  - scipy=1.5.0
  - scikit-image=0.16.2
  - pyyaml=5.3.1
  - pip:
    - opencv-python==4.4.0.44
    - cvxpy==1.1.6
    - cvxpylayers==0.1.4
    - streamlit==0.68.1
